namespace CustomException
{
    // This custom exception describes the details of the car-is-dead condition.
    // (Remember, you can also simply extend Exception.)
    public class CarIsDeadException : ApplicationException
    {
        public DateTime ErrorTimeStamp { get; set; }
        public string CauseOfError { get; set; }

        public CarIsDeadException() { }

        public CarIsDeadException(string message)
            : base(message) { }

        public CarIsDeadException(string cause, DateTime time)
            : this(cause, time, string.Empty)
        {
        }

        public CarIsDeadException(string cause, DateTime time, string message) :
            this(cause, time, message, null)
        {
        }

        public CarIsDeadException(string cause, DateTime time, string message, System.Exception inner)
            : base(message, inner)
        {
            ErrorTimeStamp = time;
            CauseOfError = cause;
        }
    }

    // this is an autogenerated code snippet template that adheres to .NET best practices.
    // to do it just write exc and then press Tab key twice
    [Serializable]
    public class MyException : Exception
    {
        public MyException() { }
        public MyException(string message) : base(message) { }
        public MyException(string message, Exception inner) : base(message, inner) { }
        protected MyException(
          System.Runtime.Serialization.SerializationInfo info,
          System.Runtime.Serialization.StreamingContext context) : base(info, context) { }
    }
}
